version: '3.8'

services:
  fx-api:
    build:
      context: ./fx-api
    container_name: fx-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
